# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Navindoor
description: Navindoor Documentation
baseurl: "/navindoor-documentation" # the subpath of your site, e.g. /blog
url: "https://deustotech.github.io" # the base hostname & protocol for your site, e.g. http://example.com
footer: The Navindoor tool is developed by
funding: This work has been supported by the Basque Department of Education under the BLUE project (ref. PI_2016_0010).
github_url: https://github.com/DeustoTech/navindoor-code

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# Enable or disable the site search
search_enabled: true

# Parameters for the upper right navigation
mobility:
  name: DeustoTech Mobility
  url: http://mobility.deustotech.eu
  img: assets/images/DeustoTech-Mobility.png

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
# ga_tracking: UA-2709176-10

destination: docs

plugins:
#A Jekyll plugin to add metadata tags for search engines and social networks to better index and display your site's content.
  - jekyll-seo-tag
  # I finally installed it by adding it in the Gemfile and running 'bundle install'
  #- jekyll-scholar
  
scholar:
  style: apa
  #style: ieee
  locale: en

  sort_by: none
  order: ascending
  
  bibliography_list_tag: none

  source: ./_bibliography
  bibliography: references.bib
  #bibliography_template: "{{reference}}"
  bibliography_template: bibliography
  #repository: ./_bibliography
  repository: ./assets/papers

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

